In [1]:
import numpy as np
a = np.array([1,0,1,0,1,0,1,1])
a.reshape(4,2)

array([[1, 0],
       [1, 0],
       [1, 0],
       [1, 1]])

In [1]:
import numpy as np
value=np.random.random()
print(value)

0.28150463173357543


In [2]:
import numpy as np
array=np.random.random((2,2))
print(array)

[[0.20063727 0.4984515 ]
 [0.74673682 0.25830443]]


In [3]:
import NumPy as np
array=np.random.randint(2, 10, size=(2,4))
print(array)

ModuleNotFoundError: No module named 'NumPy'

In [5]:
import numpy as np
array=np.random.randint(2, 10, size=(2,4))
print(array)

[[7 6 9 7]
 [4 4 9 2]]


In [6]:
array=np.zeros(3)
print(array)

[0. 0. 0.]


In [7]:
array=np.full(3, 5)
print(array)

[5 5 5]


In [8]:
array=np.eye(2)
print(array)

[[1. 0.]
 [0. 1.]]


In [9]:
array=np.ones(5)
print(array)

[1. 1. 1. 1. 1.]


In [11]:
import numpy as np
x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)

In [13]:
A=np.add(x, y)

In [14]:
A=x+y

In [15]:
import numpy as np 
a=np.array([1, 2, 3, 4, 5])
b=np.array([5,7, 13])
print(a+b)

ValueError: operands could not be broadcast together with shapes (5,) (3,) 