In [5]:
import numpy as np
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a[1,2])

5


In [6]:
print(a[1,:])

[3 4 5]


In [7]:
print(a[:, 2])

[2 5 8]


In [8]:
print(a[:,-1])

[2 5 8]


In [9]:
import numpy as np
x=np.array([[1,2],[3,4]], dtype=np.float64)
x=np.array([[5,6][7,8]],  dtype=np.float64)

<>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\TEMILADE\AppData\Local\Temp\ipykernel_6536\4100598049.py:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x=np.array([[5,6][7,8]],  dtype=np.float64)
C:\Users\TEMILADE\AppData\Local\Temp\ipykernel_6536\4100598049.py:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x=np.array([[5,6][7,8]],  dtype=np.float64)
C:\Users\TEMILADE\AppData\Local\Temp\ipykernel_6536\4100598049.py:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x=np.array([[5,6][7,8]],  dtype=np.float64)
C:\Users\TEMILADE\AppData\Local\Temp\ipykernel_6536\4100598049.py:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x=

TypeError: list indices must be integers or slices, not tuple